{% set name = "rplibs" %}
{% set version = "6.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rplibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 310aaa5a64e2b2d541be3ccf6ef609eeb3581021f6212cb0fdcb2f8d311b276a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - networkx >=2.5
    - brs_utils
    - filetype
    - chemlite
    - rr_cache
    - cobra

test:
  imports:
    - rplibs

about:
  home: https://github.com/brsynth/rplibs/tree/main
  summary: "Defines an enriched SBML structure with additional fields relative to RetroPath2 objects."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - ramez17khaled
    - breakthewall
